// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0zL5ZiB5c-m8GP7caqKctralJ9bK8lPY',
    appId: '1:398027497819:web:b9bb6da7dd98b0715dba7e',
    messagingSenderId: '398027497819',
    projectId: 'lunara-project',
    authDomain: 'lunara-project.firebaseapp.com',
    storageBucket: 'lunara-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0zL5ZiB5c-m8GP7caqKctralJ9bK8lPY',
    appId: '1:398027497819:android:b9bb6da7dd98b0715dba7e',
    messagingSenderId: '398027497819',
    projectId: 'lunara-project',
    storageBucket: 'lunara-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0zL5ZiB5c-m8GP7caqKctralJ9bK8lPY',
    appId: '1:398027497819:ios:b9bb6da7dd98b0715dba7e',
    messagingSenderId: '398027497819',
    projectId: 'lunara-project',
    storageBucket: 'lunara-project.firebasestorage.app',
    iosBundleId: 'com.lunara.lunara_app',
  );
}
